version: '3.8'

services:
  app2:
    build: 
      context: ./
      dockerfile: ./apps/app2/Dockerfile
    container_name: app2_container
    # restart: unless-stopped
    ports:
      - "10020:80"
    # entrypoint: ls -la dist/apps/app2